### ISSUE TITLE
[Bug]: API code crashing from time to time

### ISSUE THREAD

**Issue by jinzishuai** [aitok-ai/LibreChat#75]
### What happened?

<img width="896" alt="image" src="https://github.com/aitok-ai/LibreChat/assets/1074685/c3e47aff-f48b-493e-b035-ae88f32c4f41">

### Steps to Reproduce

this just happens from time to time since last release in production

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jinzishuai** [comment]
we can open any of the stopped tasks in ECS to see the error log

<img width="1290" alt="image" src="https://github.com/aitok-ai/LibreChat/assets/1074685/1bc24624-5d2c-4a16-bb9d-58cc6a44f880">

**Comment by jinzishuai** [comment]
August 16, 2023 at 19:58 (UTC+8:00) | Clearing sync timeouts before exiting... | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | There was an uncaught error: | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at new NodeError (node:internal/errors:399:5) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at ServerResponse.setHeader (node:_http_outgoing:644:11) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at ServerResponse.header (/app/node_modules/express/lib/response.js:794:10) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at ServerResponse.send (/app/node_modules/express/lib/response.js:174:12) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at abortMessage (/app/api/utils/abortMessage.js:5:28) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at ask (/app/api/server/routes/ask/openAI.js:196:20) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at async /app/api/server/routes/ask/openAI.js:45:10 { | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | code: 'ERR_HTTP_HEADERS_SENT' | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | } | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | Error: null pointer passed to rust | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at module.exports.__wbindgen_throw (/app/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:421:11) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at wasm://wasm/00b5f812:wasm-function[783]:0x712c6 | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at wasm://wasm/00b5f812:wasm-function[781]:0x712ac | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at wasm://wasm/00b5f812:wasm-function[646]:0x6c064

<br class="Apple-interchange-newline">

**Comment by jinzishuai** [comment]
August 16, 2023 at 19:58 (UTC+8:00) | at wasm://wasm/00b5f812:wasm-function[159]:0x48ced | libreChat
-- | -- | --
August 16, 2023 at 19:58 (UTC+8:00) | at Tiktoken.encode (/app/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:262:18) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at OpenAIClient.getTokenCount (/app/api/app/clients/OpenAIClient.js:180:30) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at /app/api/app/clients/BaseClient.js:534:30 | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at Array.map (<anonymous>) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at OpenAIClient.getTokenCountForMessage (/app/api/app/clients/BaseClient.js:529:57) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | req.body { | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | sender: 'User', | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | text: 'Mybatis+是什么', | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | current: true, | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | isCreatedByUser: true, | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | parentMessageId: 'bfd3fe05-374f-4f82-ab22-15661145b96d', | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | conversationId: 'c40623f8-37bd-4c7c-9f1e-6bfe6e396617', | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | messageId: 'd50587f7-da11-4b5b-a86e-3385aab53862', | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | overrideParentMessageId: null, | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | endpoint: 'openAI', | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | model: 'gpt-3.5-turbo', | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | chatGptLabel: null, | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | promptPrefix: null, | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | temperature: 1, | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | top_p: 1, | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | presence_penalty: 0, | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | frequency_penalty: 0, | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | token: null | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | } | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | freeAndResetEncoder error | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | Error: null pointer passed to rust | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at module.exports.__wbindgen_throw (/app/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:421:11) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at wasm://wasm/00b5f812:wasm-function[783]:0x712c6 | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at wasm://wasm/00b5f812:wasm-function[781]:0x712ac | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at wasm://wasm/00b5f812:wasm-function[267]:0x5eb7f | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at Tiktoken.free (/app/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:247:14) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at OpenAIClient.freeAndResetEncoder (/app/api/app/clients/OpenAIClient.js:158:23) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at OpenAIClient.getTokenCount (/app/api/app/clients/OpenAIClient.js:179:12) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at /app/api/app/clients/BaseClient.js:534:30 | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at Array.map (<anonymous>) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | at OpenAIClient.getTokenCountForMessage (/app/api/app/clients/BaseClient.js:529:57) | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | [Meilisearch] Convo not found and will index a06ee8c6-1177-4de7-8839-3fcc624ddcef | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | userMessage.tokenCount 28 | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | userMessage { | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | messageId: '941c2174-7491-4e6c-a48d-e0833b729f91', | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | parentMessageId: '5bd117b3-59e2-4453-8c8f-bd4c13e017ba', | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | conversationId: 'a06ee8c6-1177-4de7-8839-3fcc624ddcef', | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | sender: 'User', | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | text: 'mysql对百万级大表数据查询效率不高，这种查询怎么处理？', | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | isCreatedByUser: true, | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | tokenCount: 28 | libreChat
August 16, 2023 at 19:58 (UTC+8:00) | } | libreChat

**Comment by jinzishuai** [comment]
might be related to https://github.com/danny-avila/LibreChat/pull/689

> The bug was manifested with the error message "null pointer passed to rust", which occurred when multiple instances of OpenAIClient were sharing the same instances of Tiktoken. This led to scenarios where one instance had freed a tokenizer while another instance was still referencing it.

It sounds very likely: also explains why we don't see this problem in staging since only production has multiple instances.

Also
> Excellent work, thank you @ywkim. I inherited the original design for tokenizer management, and only improved it where I ran into issues. Before, the tokenizer would never get freed and would cause issues with too many simultaneous users.

**Comment by jinzishuai** [comment]
seem to have been fixed in the release  https://github.com/aitok-ai/LibreChat/releases/tag/2023-08-28a
